In [1]:
import pandas as pd 
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('dataset.csv')

In [3]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113999 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        113999 non-null  int64
 1   track_id          113999 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        113999 non-null  int64
 6   duration_ms       113999 non-null  int64
 7   explicit          113999 non-null  bool
 8   danceability      113999 non-null  float64
 9   energy            113999 non-null  float64
 10  key               113999 non-null  int64
 11  loudness          113999 non-null  float64
 12  mode              113999 non-null  int64
 13  speechiness       113999 non-null  float64
 14  acousticness      113999 non-null  float64
 15  instrumentalness  113999 non-null  float64
 16  liveness          113999 non-null  float64
 17  valence           113999 non-null  float64
 18  tempo             113999 non-null  float64
 19  time_signature    113999 non-null  int64
 20  track_genre       113999 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 18.4+ MB

In [21]:
#df_clean= df.drop(columns=["artists","track_name"], inplace=False)

In [22]:
features= ['danceability','energy','loudness','speechiness','acousticness','instrumentalness','liveness','valence','tempo']

In [23]:
#standardizing the data(make sure tempo does not outweigh energy just because the values are bigger)

In [24]:
ss= StandardScaler()

In [25]:
x=ss.fit_transform(df[features])

In [26]:
x

array([[ 0.62923855, -0.71714698,  0.300825  , ...,  0.75873531,
         0.92931467, -1.14185449],
       [-0.84590813, -1.88997393, -1.78473883, ..., -0.59121587,
        -0.79868091, -1.48970775],
       [-0.74218688, -1.12266681, -0.29328928, ..., -0.50717222,
        -1.36567947, -1.52830252],
       ...,
       [ 0.35841084, -1.24193735, -0.52413489, ..., -0.68103752,
         1.0373144 ,  0.34125863],
       [ 0.11639459, -0.53824118, -0.52294189, ...,  0.29649522,
        -0.23553949,  0.46074562],
       [-0.23510521, -0.61377919, -0.38674099, ..., -0.65267279,
         0.90231474, -1.43269958]])

In [27]:
model=  NearestNeighbors(n_neighbors=6,metric='cosine')

In [28]:
model.fit(x)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [33]:
def reccomended_song(songname):
    # find the song in our database
    matches= df[df['track_name'].str.contains(songname,case=False,na=False)]
    if matches.empty:
        return 'Song not found, try another one!'
    idx= matches.index[0]
    #find closest neighbors 
    distances, indices=model.kneighbors([x[idx]])
    #return the recommendation as output
    recommendations= df.iloc[indices[0][1:]][['track_name','artists','album_name']]
    return recommendations

In [35]:
reccomended_song('believer')

,track_name,artists,album_name
125,Believer (Remix),Ben Woodward,Believer (Remix)
25684,Kleine Taschenlampe brenn,Thomas Anders;Giraffenaffen,Giraffenaffen 7 - Die große Geburtstagsfeier (...
98716,happy to be sad,Ben Platt,Reverie
70095,光年之外 (電影 《Passengers》 中國區主題曲),G.E.M.,光年之外 (電影 《Passengers》 中國區主題曲)
1719,Vai C Bom,Zé Bigode Orquestra,Clube da Fumaça

In [36]:
df.loc[df['artists']=='Justin Beiber']

Empty DataFrame
Columns: [Unnamed: 0, track_id, artists, album_name, track_name, popularity, duration_ms, explicit, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature, track_genre]
Index: []

[0 rows x 21 columns]

In [41]:
df['artists'].str.contains('Beiber').value_counts()

artists
False    113999
Name: count, dtype: int64

In [46]:
df[df['artists'].str.contains('Katy Perry')]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
19550,19550,2yBWKK84uebv35lGajIMhc,Thomas Rhett;Katy Perry,Where We Started,Where We Started,62,182026,False,0.600,0.533,...,-6.555,1,0.0256,0.27200,0.000000,0.0927,0.626,139.940,4,country
20002,20002,5nCthAh3jt4xKuLJAifAaR,Katy Perry,Harleys In Hawaii,Harleys In Hawaii,73,185815,False,0.722,0.757,...,-6.207,0,0.1320,0.18500,0.000006,0.1260,0.721,140.094,4,dance
20058,20058,3B4etxytImrRKQgV3XHjnR,Katy Perry,Smile,Harleys In Hawaii,78,185480,False,0.721,0.751,...,-6.203,0,0.1250,0.16200,0.000007,0.1180,0.738,140.095,4,dance
20212,20212,5kihSsgmpiecsJjjKI80QR,Katy Perry,Workout Hits 2023,I Kissed A Girl,3,209866,False,0.824,0.682,...,-4.624,0,0.1450,0.00126,0.204000,0.0503,0.390,130.026,4,dance
20214,20214,06frz7np2mUzt0wUTBERYP,Katy Perry,Rock Christmas 2022 - The Very Best Of,Cozy Little Christmas,1,182520,False,0.775,0.608,...,-6.264,1,0.1280,0.12800,0.000000,0.0895,0.560,137.494,4,dance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89555,89555,4au7FRcgZzChASRYu279xH,Daddy Yankee;Katy Perry;Snow,Con Calma (Remix),Con Calma - Remix,63,181280,False,0.736,0.868,...,-3.010,0,0.0454,0.16600,0.000001,0.0419,0.613,94.026,4,reggaeton
99769,99769,7IByJvSqRFltGyiiIiL4wn,John Mayer;Katy Perry,Paradise Valley,Who You Love (feat. Katy Perry),64,249933,False,0.694,0.351,...,-10.920,1,0.0382,0.81300,0.001650,0.0970,0.691,145.907,4,singer-songwriter
102769,102769,7IByJvSqRFltGyiiIiL4wn,John Mayer;Katy Perry,Paradise Valley,Who You Love (feat. Katy Perry),64,249933,False,0.694,0.351,...,-10.920,1,0.0382,0.81300,0.001650,0.0970,0.691,145.907,4,songwriter
109013,109013,2XWjPtKdi5sucFYtVav07d,Zedd;Katy Perry,365,365,66,181899,False,0.745,0.693,...,-5.479,0,0.0340,0.33900,0.000000,0.1230,0.248,98.039,4,techno
109701,109701,0ywzvARVqoxQOJpaswRe9E,Zedd;Katy Perry,365 (Remixes),365 - Zedd Remix,46,236286,False,0.784,0.595,...,-6.816,1,0.0413,0.00476,0.007270,0.0590,0.183,124.019,4,techno